name: Create PR peter evans
on:
  push:
    branches:
      - dev
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.PAT_SECRET}}
          branch: int
          commit-message: This is a test
          title: Create PR
          body: This is a test
          base: dev
